### ISSUE TITLE
No such element or plugin 'rosaudiosink'

### ISSUE THREAD

**Issue by matbeedotcom** [luxonis/rae-ros#27]
I had to add a version of this to the Dockerfile to get the gstreamer modules enabled- I can submit a PR with an updated Dockerfile but I don't want to assume the base dockerfile should have gst bridge.
```
git clone https://github.com/BrettRD/ros-gst-bridge.git /ws/src/ros-gst-bridge
cd /ws
rosdep update
rosdep install --from-paths /ws/src/ --ignore-src -r -y
colcon build
source /ws/install/setup.zsh
```

Now I can run the example `gst-launch-1.0 alsasrc device="hw:0,1" ! audio/x-raw,rate=48000,format=S32LE ! audioconvert ! spectrascope ! videoconvert ! video/x-raw,width=160,height=80 ! fbdevsink` commands just fine

**Comment by matbeedotcom** [comment]
Feel free to close this if its a known roadmap task

**Comment by Serafadam** [comment]
Hi @matbee-eth, which docker image are you using? `gst_bridge` is set up in `depthai_ws`/`underlay_ws` in `humble` image

**Comment by danilo-pejovic** [comment]
I built another image from source (since I assume you have an issue when you are trying to build your own image) to check if we maybe incorrectly sourced something during latest changes - but everything worked ok for me. 

Can you check if either of folders /underlay_ws or /depthai_ws exists in your image?
