### ISSUE TITLE
PWM resources are not released on container shutdown

### ISSUE THREAD

**Issue by sskorol** [luxonis/rae-ros#45]
Steps:
- run `luxonis/rae-ros-robot:humble` docker image
- run `bringup.launch.py`
- `ctr + c` to stop the nodes
- exit container
- start container once again

Expected: there are no errors during startup
Actual: `/ws/src/rae-ros/entrypoint.sh: line 5: echo: write error: Device or resource busy` is displayed.

I believe we should release PWMs before shutting down the container. The error comes from [here](https://github.com/luxonis/rae-ros/blob/humble/entrypoint.sh#L5) when we `echo` to PWMs.

**Comment by danilo-pejovic** [comment]
That error is safe to ignore - exporting those files just means we are creating means to control the motors, once the container is powered down and new one is started it will try to create those same files (and fail because they already exist) but it shouldnt have any issue controlling the motors even if it wasnt the process that spawned those files. 

It would be helpful to check if files are already exported before trying to export them again - we will probably add those checks relatively soon.
